# Generated by Django 5.2.6 on 2026-07-21 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recorder", "0023_recordersettings_app_latest_commit_sha_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessengerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Solange aus, sendet dieses Plugin nichts - auch nicht automatisch nach dem Schneiden.",
                        verbose_name="Aktiviert",
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        default="x32-recorder",
                        help_text="Name, unter dem dieses Gerät in der Signal-App des verknüpften Kontos erscheint.",
                        max_length=64,
                        verbose_name="Geräte-Name",
                    ),
                ),
                (
                    "linked",
                    models.BooleanField(
                        default=False,
                        help_text="Nur eine Anzeige, kein Schalter - wird beim erfolgreichen Abschluss der Geräte-Verknüpfung automatisch gesetzt (siehe linking.py).",
                        verbose_name="Verknüpft",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SignalTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Name")),
                (
                    "group_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Über 'Gruppen laden' im Verknüpfen-Schritt auswählen, oder von Hand eintragen.",
                        max_length=256,
                        verbose_name="Signal-Gruppen-ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="Aktiv")),
                (
                    "auto_send_on_clip_export",
                    models.BooleanField(
                        default=False,
                        help_text="Frisch geschnittene Song-Clips automatisch an dieses Ziel senden, sobald ihr Browser-Mix fertig ist.",
                        verbose_name="Auto-Senden nach Schnitt",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SendLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("success", models.BooleanField(default=False)),
                ("error", models.CharField(blank=True, default="", max_length=512)),
                (
                    "recording",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messenger_send_logs",
                        to="recorder.recording",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="send_logs",
                        to="x32_recorder_messenger_plugin.signaltarget",
                    ),
                ),
            ],
        ),
    ]
