# Generated by Django 5.2.6 on 2026-07-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("x32_recorder_messenger_plugin", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="messengersettings",
            name="enabled",
            field=models.BooleanField(
                default=False,
                help_text="Nicht zu verwechseln mit dem 'Aktiviert' oben in der Plugin-Zeile (das lädt nur das Plugin) - hier: solange aus, sendet dieses Plugin nichts, auch nicht automatisch nach dem Schneiden, selbst wenn Ziel-Gruppen konfiguriert sind.",
                verbose_name="Versand aktiviert",
            ),
        ),
    ]
